import { Movie, Genre, MovieDetails, CastMember } from "@/types/movie";

export const GENRES: Genre[] = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Sci-Fi" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    media_type: "movie",
    title: "Dune: Part Two",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    release_date: "2024-02-27",
    vote_average: 8.3,
    vote_count: 5200,
    genre_ids: [878, 12],
    popularity: 980.5,
    adult: false,
    original_language: "en",
    original_title: "Dune: Part Two",
    video: false,
    runtime: 166,
    tagline: "Long live the fighters.",
    trailer_key: "Way9Dexny3w",
  },
  {
    id: 2,
    title: "Oppenheimer",
    overview: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    release_date: "2023-07-19",
    vote_average: 8.1,
    vote_count: 7800,
    genre_ids: [18, 36],
    popularity: 620.3,
    adult: false,
    original_language: "en",
    original_title: "Oppenheimer",
    video: false,
    runtime: 180,
    tagline: "The world forever changes.",
    trailer_key: "uYPbbksJxIg",
  },
  {
    id: 3,
    title: "Guardians of the Galaxy Vol. 3",
    overview: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and protect one of their own.",
    poster_path: "/r2J02Z2OpNTctfOSN1oDITDCFYV.jpg",
    backdrop_path: "/5YZbUmjbMa3ClvSW1Wj3D6XGkVA.jpg",
    release_date: "2023-05-05",
    vote_average: 7.9,
    vote_count: 6100,
    genre_ids: [28, 12, 878],
    popularity: 510.8,
    adult: false,
    original_language: "en",
    original_title: "Guardians of the Galaxy Vol. 3",
    video: false,
    runtime: 150,
    tagline: "Once more with feeling.",
    trailer_key: "u3V5KDHRQvk",
  },
  {
    id: 4,
    title: "The Dark Knight",
    overview: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    release_date: "2008-07-14",
    vote_average: 9.0,
    vote_count: 32000,
    genre_ids: [28, 80, 18],
    popularity: 850.2,
    adult: false,
    original_language: "en",
    original_title: "The Dark Knight",
    video: false,
    runtime: 152,
    tagline: "Why so serious?",
    trailer_key: "EXeTwQWrcwY",
  },
  {
    id: 5,
    title: "Interstellar",
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    release_date: "2014-11-05",
    vote_average: 8.7,
    vote_count: 35000,
    genre_ids: [878, 12, 18],
    popularity: 720.1,
    adult: false,
    original_language: "en",
    original_title: "Interstellar",
    video: false,
    runtime: 169,
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    trailer_key: "zSWdZVtXT7E",
  },
  {
    id: 6,
    title: "Avatar: The Way of Water",
    overview: "Set more than a decade after the events of the first film, learn the story of the Sully family, the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    release_date: "2022-12-14",
    vote_average: 7.6,
    vote_count: 15800,
    genre_ids: [878, 12],
    popularity: 455.9,
    adult: false,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    video: false,
    runtime: 192,
    tagline: "Return to Pandora.",
    trailer_key: "d9MyW72ELq0",
  },
  {
    id: 7,
    title: "Inception",
    overview: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg",
    release_date: "2010-07-15",
    vote_average: 8.8,
    vote_count: 38000,
    genre_ids: [28, 878, 9648],
    popularity: 680.4,
    adult: false,
    original_language: "en",
    original_title: "Inception",
    video: false,
    runtime: 148,
    tagline: "Your mind is the scene of the crime.",
    trailer_key: "YoHD9XEInc0",
  },
  {
    id: 8,
    title: "Spider-Man: Across the Spider-Verse",
    overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop_path: "/4HodYYY1Ve7yl71MR25g2yP0LMPZ.jpg",
    release_date: "2023-05-31",
    vote_average: 8.7,
    vote_count: 9200,
    genre_ids: [16, 28, 12],
    popularity: 590.7,
    adult: false,
    original_language: "en",
    original_title: "Spider-Man: Across the Spider-Verse",
    video: false,
    runtime: 140,
    tagline: "It's how you wear the mask that matters.",
    trailer_key: "cqGjhVJWtEg",
  },
  {
    id: 9,
    title: "The Shawshank Redemption",
    overview: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    poster_path: "/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    release_date: "1994-09-23",
    vote_average: 9.3,
    vote_count: 26000,
    genre_ids: [18, 80],
    popularity: 420.5,
    adult: false,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    video: false,
    runtime: 142,
    tagline: "Fear can hold you prisoner. Hope can set you free.",
    trailer_key: "NmzuHjWmXOc",
  },
  {
    id: 10,
    title: "Killers of the Flower Moon",
    overview: "Members of the Osage Nation in the United States are murdered under mysterious circumstances in the 1920s sparking a major FBI investigation.",
    poster_path: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
    backdrop_path: "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
    release_date: "2023-10-18",
    vote_average: 7.6,
    vote_count: 4200,
    genre_ids: [80, 18, 36],
    popularity: 390.2,
    adult: false,
    original_language: "en",
    original_title: "Killers of the Flower Moon",
    video: false,
    runtime: 206,
    tagline: "There will be blood.",
    trailer_key: "EP34Yoxs3FQ",
  },
  {
    id: 11,
    title: "Poor Things",
    overview: "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    poster_path: "/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
    backdrop_path: "/mQIEbC0piomB0jEdMfWITqVUZrs.jpg",
    release_date: "2023-12-07",
    vote_average: 8.0,
    vote_count: 3800,
    genre_ids: [878, 35, 18],
    popularity: 370.6,
    adult: false,
    original_language: "en",
    original_title: "Poor Things",
    video: false,
    runtime: 141,
    tagline: "She's not who you think.",
    trailer_key: "RlbR5N6veqw",
  },
  {
    id: 12,
    title: "Mission: Impossible – Dead Reckoning",
    overview: "Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.",
    poster_path: "/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
    backdrop_path: "/1hJdVM8RrVlHMZYKoADaESmMd3C.jpg",
    release_date: "2023-07-12",
    vote_average: 7.7,
    vote_count: 5500,
    genre_ids: [28, 12, 53],
    popularity: 445.3,
    adult: false,
    original_language: "en",
    original_title: "Mission: Impossible – Dead Reckoning Part One",
    video: false,
    runtime: 163,
    tagline: "The mission is everything.",
    trailer_key: "avz9HMxSEBs",
  },
  {
    id: 13,
    title: "The Batman",
    overview: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop_path: "/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    release_date: "2022-03-04",
    vote_average: 7.8,
    vote_count: 14000,
    genre_ids: [80, 9648, 28],
    popularity: 488.1,
    adult: false,
    original_language: "en",
    original_title: "The Batman",
    video: false,
    runtime: 176,
    tagline: "Unmask the truth.",
    trailer_key: "mqqft2x_Aa4",
  },
  {
    id: 14,
    title: "Everything Everywhere All at Once",
    overview: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdrop_path: "/AbRYbNNKseqBgFRxijDcTpKgwwv.jpg",
    release_date: "2022-03-25",
    vote_average: 8.0,
    vote_count: 8300,
    genre_ids: [28, 12, 878],
    popularity: 360.9,
    adult: false,
    original_language: "en",
    original_title: "Everything Everywhere All at Once",
    video: false,
    runtime: 139,
    tagline: "The universe is so much bigger than you realize.",
    trailer_key: "wxN1T1uxQ2g",
  },
  {
    id: 15,
    title: "Top Gun: Maverick",
    overview: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop_path: "/AkJQpZp9WoNdj7pLYSj1L0RcMMN.jpg",
    release_date: "2022-05-27",
    vote_average: 8.3,
    vote_count: 12800,
    genre_ids: [28, 18],
    popularity: 530.2,
    adult: false,
    original_language: "en",
    original_title: "Top Gun: Maverick",
    video: false,
    runtime: 131,
    tagline: "Feel the need.",
    trailer_key: "qSqVVswa420",
  },
  {
    id: 16,
    title: "Wonka",
    overview: "The story of how the world's greatest inventor, magician and chocolate-maker became the beloved Willy Wonka we know today.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path: "/aCEW4HNjULIMX5PjgWE9VHSxnCq.jpg",
    release_date: "2023-12-15",
    vote_average: 7.2,
    vote_count: 4600,
    genre_ids: [35, 14, 10751],
    popularity: 420.8,
    adult: false,
    original_language: "en",
    original_title: "Wonka",
    video: false,
    runtime: 116,
    tagline: "Every dream begins with a dreamer.",
    trailer_key: "otNh9bTjXWg",
  },
  {
    id: 17,
    title: "Saltburn",
    overview: "Struggling to find his place at Oxford University, student Oliver Quick finds himself drawn into the world of the charming and aristocratic Felix Catton.",
    poster_path: "/qjhahNLSZ705B5JP92YMEYPocPz.jpg",
    backdrop_path: "/qR5nC2R1F6fBRkWfQzaJhrlKi1p.jpg",
    release_date: "2023-11-16",
    vote_average: 7.3,
    vote_count: 3100,
    genre_ids: [53, 18, 9648],
    popularity: 305.4,
    adult: false,
    original_language: "en",
    original_title: "Saltburn",
    video: false,
    runtime: 127,
    tagline: "You'll be obsessed.",
    trailer_key: "VJSi9tj_l7U",
  },
  {
    id: 18,
    title: "Avengers: Endgame",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    release_date: "2019-04-24",
    vote_average: 8.4,
    vote_count: 24000,
    genre_ids: [12, 878, 28],
    popularity: 760.3,
    adult: false,
    original_language: "en",
    original_title: "Avengers: Endgame",
    video: false,
    runtime: 181,
    tagline: "Whatever it takes.",
    trailer_key: "TcMBFSGVi1c",
  },
  {
    id: 19,
    title: "Parasite",
    overview: "All unemployed, Ki-taek's family takes a special interest in the affluent and naive Park family, as they ingratiate themselves into their lives and get entangled in an unexpected incident.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    vote_count: 18900,
    genre_ids: [35, 18, 53],
    popularity: 400.7,
    adult: false,
    original_language: "ko",
    original_title: "기생충",
    video: false,
    runtime: 132,
    tagline: "Act like you own the place.",
    trailer_key: "5xH0HfJHsaY",
  },
  {
    id: 20,
    title: "The Godfather",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the family business.",
    poster_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    release_date: "1972-03-24",
    vote_average: 9.2,
    vote_count: 20000,
    genre_ids: [18, 80],
    popularity: 380.6,
    adult: false,
    original_language: "en",
    original_title: "The Godfather",
    video: false,
    runtime: 175,
    tagline: "An offer you can't refuse.",
    trailer_key: "sY1S34973zA",
  },
  {
    id: 21,
    title: "Joker: Folie à Deux",
    overview: "Arthur Fleck is institutionalized at Arkham awaiting trial for his crimes as Joker. While struggling with his dual identity, Arthur not only stumbles upon true love, but also finds the music that's always been inside him.",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "/f2bVqRMOCHrfFoOjGWVhIHBsNf3.jpg",
    release_date: "2024-10-04",
    vote_average: 5.3,
    vote_count: 2800,
    genre_ids: [80, 18, 10402],
    popularity: 285.4,
    adult: false,
    original_language: "en",
    original_title: "Joker: Folie à Deux",
    video: false,
    runtime: 138,
    tagline: "Comedy. Love. Chaos.",
    trailer_key: "5oqFmJpCRSA",
  },
  {
    id: 22,
    title: "Gladiator II",
    overview: "After his home is conquered by the tyrannical emperors who now lead Rome, Lucius is forced to enter the Colosseum and must look to his past to find strength to return the glory of Rome to its people.",
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop_path: "/euYIwmwkmz95mnXvufEJO0RFJJI.jpg",
    release_date: "2024-11-22",
    vote_average: 7.0,
    vote_count: 3100,
    genre_ids: [28, 12, 18],
    popularity: 410.2,
    adult: false,
    original_language: "en",
    original_title: "Gladiator II",
    video: false,
    runtime: 148,
    tagline: "The epic continues.",
    trailer_key: "Pm4MoarU5RI",
  },
  {
    id: 23,
    title: "Deadpool & Wolverine",
    overview: "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    poster_path: "/8cdWjvZQUExUUTzyp4SQFXyHucR.jpg",
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    release_date: "2024-07-26",
    vote_average: 7.9,
    vote_count: 6200,
    genre_ids: [28, 12, 35],
    popularity: 620.8,
    adult: false,
    original_language: "en",
    original_title: "Deadpool & Wolverine",
    video: false,
    runtime: 128,
    tagline: "Come together.",
    trailer_key: "73_1biulkYk",
  },
  {
    id: 24,
    title: "Alien: Romulus",
    overview: "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
    backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
    release_date: "2024-08-16",
    vote_average: 7.3,
    vote_count: 3400,
    genre_ids: [878, 27],
    popularity: 340.5,
    adult: false,
    original_language: "en",
    original_title: "Alien: Romulus",
    video: false,
    runtime: 119,
    tagline: "Do not look away.",
    trailer_key: "KaqD5C0RkCk",
  },
  {
    id: 25,
    title: "Inside Out 2",
    overview: "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who've long been running a successful operation by all accounts, aren't sure how to feel when Anxiety shows up.",
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2smM.jpg",
    backdrop_path: "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
    release_date: "2024-06-14",
    vote_average: 7.7,
    vote_count: 4800,
    genre_ids: [16, 12, 10751],
    popularity: 510.3,
    adult: false,
    original_language: "en",
    original_title: "Inside Out 2",
    video: false,
    runtime: 100,
    tagline: "She's got a lot of feelings.",
    trailer_key: "LEjhY15eCx0",
  },
  {
    id: 26,
    title: "Pulp Fiction",
    overview: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    release_date: "1994-09-23",
    vote_average: 8.9,
    vote_count: 28000,
    genre_ids: [53, 80],
    popularity: 450.9,
    adult: false,
    original_language: "en",
    original_title: "Pulp Fiction",
    video: false,
    runtime: 154,
    tagline: "You won't know the facts until you've seen the fiction.",
    trailer_key: "s7EdQ4FqbhY",
  },
  {
    id: 27,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.",
    poster_path: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop_path: "/pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg",
    release_date: "2001-12-19",
    vote_average: 8.9,
    vote_count: 25000,
    genre_ids: [12, 14, 28],
    popularity: 380.4,
    adult: false,
    original_language: "en",
    original_title: "The Lord of the Rings: The Fellowship of the Ring",
    video: false,
    runtime: 178,
    tagline: "One ring to rule them all.",
    trailer_key: "V75dMMIW2B4",
  },
  {
    id: 28,
    title: "Tenet",
    overview: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
    poster_path: "/k68nPLbIST6NP96JmTxmZijAbMV.jpg",
    backdrop_path: "/wzJRB4MKi3yK138bW1Up1zyglyE.jpg",
    release_date: "2020-08-26",
    vote_average: 7.3,
    vote_count: 13000,
    genre_ids: [28, 878, 12],
    popularity: 330.7,
    adult: false,
    original_language: "en",
    original_title: "Tenet",
    video: false,
    runtime: 150,
    tagline: "Time runs out.",
    trailer_key: "LdOM0x0XDMo",
  },
  {
    id: 29,
    title: "Blade Runner 2049",
    overview: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop_path: "/ilRyazdMJwN05exqhwK4tMKBYZs.jpg",
    release_date: "2017-10-06",
    vote_average: 7.9,
    vote_count: 15000,
    genre_ids: [878, 18],
    popularity: 290.5,
    adult: false,
    original_language: "en",
    original_title: "Blade Runner 2049",
    video: false,
    runtime: 164,
    tagline: "The key to the future is finally unearthed.",
    trailer_key: "gCcx85zbxz4",
  },
  {
    id: 30,
    title: "1917",
    overview: "At the height of the First World War, two young British soldiers must cross enemy territory and deliver a message that will stop a deadly attack on hundreds of soldiers.",
    poster_path: "/iZf0KyrE25z1sage4SYFLCCrMi9.jpg",
    backdrop_path: "/fhqoHsd4364tHmtmRGQBWkamAmK.jpg",
    release_date: "2020-01-10",
    vote_average: 8.3,
    vote_count: 11000,
    genre_ids: [28, 18, 10752],
    popularity: 310.2,
    adult: false,
    original_language: "en",
    original_title: "1917",
    video: false,
    runtime: 119,
    tagline: "Time is the enemy.",
    trailer_key: "YqNYrYUiMfg",
  },
];

export const MOCK_TV_SHOWS: Movie[] = [
  {
    id: 1396,
    media_type: "tv",
    imdb_id: "tt0903747",
    name: "Breaking Bad",
    title: "Breaking Bad",
    overview: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's financial future.",
    poster_path: "/ggFHVNu6YYI5L9pIChRoQ0euXy5.jpg",
    backdrop_path: "/eSzhy6RDEJU48tLv5cur8EDlYuU.jpg",
    first_air_date: "2008-01-20",
    release_date: "2008-01-20",
    original_name: "Breaking Bad",
    original_title: "Breaking Bad",
    vote_average: 9.5,
    vote_count: 15000,
    genre_ids: [18, 80],
    popularity: 950.8,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "HhesaQJeFzw",
  },
  {
    id: 1399,
    media_type: "tv",
    imdb_id: "tt0944947",
    name: "Game of Thrones",
    title: "Game of Thrones",
    overview: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy emerges from the far North.",
    poster_path: "/u3bZgnrm2E0vF4b10qNw154TU2L.jpg",
    backdrop_path: "/gX8SurPiQFfo8PtME5Real1mCO2.jpg",
    first_air_date: "2011-04-17",
    release_date: "2011-04-17",
    original_name: "Game of Thrones",
    original_title: "Game of Thrones",
    vote_average: 9.3,
    vote_count: 18000,
    genre_ids: [10765, 18, 10759],
    popularity: 880.5,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "KPLWWIOCOOQ",
  },
  {
    id: 66732,
    media_type: "tv",
    imdb_id: "tt4574334",
    name: "Stranger Things",
    title: "Stranger Things",
    overview: "When a young boy disappears, his friends, family and local police go on a search adventure to find him and uncover a mystery involving secret government experiments, terrifying supernatural forces and a strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfLnwC2t5Ew4J.jpg",
    backdrop_path: "/c0RY6lMVFo2ztsGk7tXVmhJ8F9R.jpg",
    first_air_date: "2016-07-15",
    release_date: "2016-07-15",
    original_name: "Stranger Things",
    original_title: "Stranger Things",
    vote_average: 8.7,
    vote_count: 12000,
    genre_ids: [18, 10765, 9648],
    popularity: 720.3,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "b9ncM1qP7J4",
  },
  {
    id: 65494,
    media_type: "tv",
    imdb_id: "tt4786824",
    name: "The Crown",
    title: "The Crown",
    overview: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
    poster_path: "/imposGUeuKbWwCkQKePMEj0w7yv.jpg",
    backdrop_path: "/ugL0NZ5vBZ43hbVNBzcKq4BsJa8.jpg",
    first_air_date: "2016-11-04",
    release_date: "2016-11-04",
    original_name: "The Crown",
    original_title: "The Crown",
    vote_average: 8.6,
    vote_count: 8500,
    genre_ids: [18, 10768],
    popularity: 580.7,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "JWqqn9x-lS8",
  },
  {
    id: 82856,
    media_type: "tv",
    imdb_id: "tt8111088",
    name: "The Mandalorian",
    title: "The Mandalorian",
    overview: "After the fall of the Empire, a lone bounty hunter operatives in the outer reaches of the galaxy, far from the authority of the New Republic.",
    poster_path: "/eU459sPEeHYjg5V5rMLQVcnMY3Z.jpg",
    backdrop_path: "/aJn9XeesqWrlMEiKPfi1MUlNProductId.jpg",
    first_air_date: "2019-11-12",
    release_date: "2019-11-12",
    original_name: "The Mandalorian",
    original_title: "The Mandalorian",
    vote_average: 8.7,
    vote_count: 9800,
    genre_ids: [10759, 10765, 37],
    popularity: 650.2,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "aOAJc97YQnU",
  },
  {
    id: 2316,
    media_type: "tv",
    imdb_id: "tt0386676",
    name: "The Office",
    title: "The Office",
    overview: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.",
    poster_path: "/6u5yw3x1p65VlUWhH8582vzsFI.jpg",
    backdrop_path: "/3QX5Md13bXJkWa4bvM4LSDWFoOY.jpg",
    first_air_date: "2005-03-24",
    release_date: "2005-03-24",
    original_name: "The Office",
    original_title: "The Office",
    vote_average: 9.0,
    vote_count: 14000,
    genre_ids: [35],
    popularity: 520.1,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "GMaQkVw3T8E",
  },
  {
    id: 19885,
    media_type: "tv",
    imdb_id: "tt1475582",
    name: "Sherlock",
    title: "Sherlock",
    overview: "A modern update finds the famous sleuth and his doctor partner solving crimes in 21st century London.",
    poster_path: "/xUL1FT8LNxlqnkbD7dLrfC4Lcx4.jpg",
    backdrop_path: "/bPnAAJsUyIc9G9yrIQn1LwLz0P3.jpg",
    first_air_date: "2010-07-25",
    release_date: "2010-07-25",
    original_name: "Sherlock",
    original_title: "Sherlock",
    vote_average: 9.1,
    vote_count: 10500,
    genre_ids: [80, 18, 9648],
    popularity: 480.5,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "gtjJQwI1c30",
  },
  {
    id: 71912,
    media_type: "tv",
    imdb_id: "tt5180504",
    name: "The Witcher",
    title: "The Witcher",
    overview: "Geralt of Rivia, a monster slayer for hire, journeys through a world of humans and nonhumans seeking his destiny.",
    poster_path: "/dMWzrO7s8xo6zDd0LKJ6sXEsDd6.jpg",
    backdrop_path: "/zZJLRpfz6hT8kPY5pCn6Y1ZlSV5.jpg",
    first_air_date: "2019-12-20",
    release_date: "2019-12-20",
    original_name: "The Witcher",
    original_title: "The Witcher",
    vote_average: 8.4,
    vote_count: 7200,
    genre_ids: [10765, 12, 18],
    popularity: 420.3,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "ndl1W4ltcmg",
  },
  {
    id: 63247,
    media_type: "tv",
    imdb_id: "tt0475784",
    name: "Westworld",
    title: "Westworld",
    overview: "At the intersection of the near future and the reimagined past, waits a world in which every human appetite can be indulged without consequence.",
    poster_path: "/n8fHvU4cz5nDW0bqMJXtnVoPnBj.jpg",
    backdrop_path: "/rDlvpJ8lFGY2aNlJr6nL7qKJhUi.jpg",
    first_air_date: "2016-10-02",
    release_date: "2016-10-02",
    original_name: "Westworld",
    original_title: "Westworld",
    vote_average: 8.5,
    vote_count: 6800,
    genre_ids: [18, 10765, 9648],
    popularity: 380.2,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "FXCz2wyy90s",
  },
  {
    id: 100088,
    media_type: "tv",
    imdb_id: "tt3581920",
    name: "The Last of Us",
    title: "The Last of Us",
    overview: "After a fungal outbreak wipes out most of humanity, Joel, a hardened survivor, is tasked with escorting Ellie, a 14-year-old girl who is immune to the virus, through a dangerous post-pandemic world.",
    poster_path: "/uKvVjHNWL8DH9rt89PmeZ8ub2N1.jpg",
    backdrop_path: "/gbLnKhKvpPPuCSPsQ5W3VwscUAV.jpg",
    first_air_date: "2023-01-15",
    release_date: "2023-01-15",
    original_name: "The Last of Us",
    original_title: "The Last of Us",
    vote_average: 8.8,
    vote_count: 5600,
    genre_ids: [18, 10765, 10759],
    popularity: 550.4,
    adult: false,
    original_language: "en",
    video: false,
    trailer_key: "ggJdvCYd5wQ",
  },
];

const REAL_IDS: Record<number, { id: number; imdb_id: string }> = {
  1: { id: 693134, imdb_id: "tt15239678" },
  2: { id: 872585, imdb_id: "tt15398776" },
  3: { id: 447365, imdb_id: "tt6791350" },
  4: { id: 155, imdb_id: "tt0468569" },
  5: { id: 157336, imdb_id: "tt0816692" },
  6: { id: 76600, imdb_id: "tt1630029" },
  7: { id: 27205, imdb_id: "tt1375666" },
  8: { id: 569094, imdb_id: "tt9362722" },
  9: { id: 278, imdb_id: "tt0111161" },
  10: { id: 466420, imdb_id: "tt5537002" },
  11: { id: 792307, imdb_id: "tt14273588" },
  12: { id: 575264, imdb_id: "tt9603224" },
  13: { id: 414906, imdb_id: "tt1877830" },
  14: { id: 772071, imdb_id: "tt6710474" },
  15: { id: 361743, imdb_id: "tt1745960" },
  16: { id: 787699, imdb_id: "tt6166392" },
  17: { id: 930564, imdb_id: "tt17351924" },
  18: { id: 299534, imdb_id: "tt4154796" },
  19: { id: 496243, imdb_id: "tt6751668" },
  20: { id: 238, imdb_id: "tt0068646" },
  21: { id: 889737, imdb_id: "tt21226505" },
  22: { id: 558449, imdb_id: "tt9660852" },
  23: { id: 533535, imdb_id: "tt6263850" },
  24: { id: 945961, imdb_id: "tt18412256" },
  25: { id: 1022789, imdb_id: "tt22022452" },
  26: { id: 680, imdb_id: "tt0110912" },
  27: { id: 120, imdb_id: "tt0120737" },
  28: { id: 577922, imdb_id: "tt6723592" },
  29: { id: 335984, imdb_id: "tt1856101" },
  30: { id: 530915, imdb_id: "tt8579674" },
};

MOCK_MOVIES.forEach((movie) => {
  const mapping = REAL_IDS[movie.id];
  if (mapping) {
    movie.imdb_id = mapping.imdb_id;
    movie.id = mapping.id;
  }
});

export const MOCK_CAST: CastMember[] = [
  { id: 101, name: "Timothée Chalamet", character: "Paul Atreides", profile_path: "/BE2sdjpgsa2rNTFa66f7upkaOP.jpg", order: 0 },
  { id: 102, name: "Zendaya", character: "Chani", profile_path: "/6TE2AlOZqo4oMYtFPdTjKGrnUzA.jpg", order: 1 },
  { id: 103, name: "Rebecca Ferguson", character: "Lady Jessica", profile_path: "/lJloTOheuQSirSLXNA3JHsrMNfH.jpg", order: 2 },
  { id: 104, name: "Austin Butler", character: "Feyd-Rautha", profile_path: "/6FiDtx2KFm4kcgm3CW39nS1bNPJ.jpg", order: 3 },
  { id: 105, name: "Florence Pugh", character: "Princess Irulan", profile_path: "/pBdeTPgxNIjBGjl93dFBXHBveIp.jpg", order: 4 },
  { id: 106, name: "Josh Brolin", character: "Gurney Halleck", profile_path: "/3MlWCH5jMX4gO8sFbUSXcuPDOb0.jpg", order: 5 },
];

export function getGenreNames(genreIds: number[]): string[] {
  return genreIds
    .map((id) => GENRES.find((g) => g.id === id)?.name)
    .filter(Boolean) as string[];
}

export function getMovieById(id: number): MovieDetails | undefined {
  const movie = MOCK_MOVIES.find((m) => m.id === id);
  if (!movie) return undefined;
  return {
    ...movie,
    media_type: "movie" as const,
    genres: movie.genre_ids.map((gid) => GENRES.find((g) => g.id === gid)).filter(Boolean) as Genre[],
    credits: { id: movie.id, cast: MOCK_CAST, crew: [] },
    similar: MOCK_MOVIES.filter((m) => m.id !== id && m.genre_ids.some((g) => movie.genre_ids.includes(g))).slice(0, 12).map(m => ({ ...m, media_type: "movie" as const })),
  };
}

export function getTvById(id: number): MovieDetails | undefined {
  const show = MOCK_TV_SHOWS.find((m) => m.id === id);
  if (!show) return undefined;

  return {
    ...show,
    media_type: "tv" as const,
    genres: show.genre_ids.map((gid) => GENRES.find((g) => g.id === gid)).filter(Boolean) as Genre[],
    credits: { id: show.id, cast: MOCK_CAST, crew: [] },
    similar: MOCK_TV_SHOWS.filter((m) => m.id !== id && m.genre_ids.some((g) => show.genre_ids.includes(g))).slice(0, 12).map(m => ({ ...m, media_type: "tv" as const })),
  };
}

export function getTrending(): Movie[] {
  return [...MOCK_MOVIES].sort((a, b) => b.popularity - a.popularity).slice(0, 20).map(m => ({ ...m, media_type: "movie" as const }));
}

export function getTopRated(): Movie[] {
  return [...MOCK_MOVIES].sort((a, b) => b.vote_average - a.vote_average).slice(0, 20).map(m => ({ ...m, media_type: "movie" as const }));
}

export function getNewReleases(): Movie[] {
  return [...MOCK_MOVIES].sort((a, b) => new Date(b.release_date).getTime() - new Date(a.release_date).getTime()).slice(0, 20).map(m => ({ ...m, media_type: "movie" as const }));
}

export function getByGenre(genreId: number): Movie[] {
  return MOCK_MOVIES.filter((m) => m.genre_ids.includes(genreId)).slice(0, 20).map(m => ({ ...m, media_type: "movie" as const }));
}

export function searchMovies(query: string): Movie[] {
  const q = query.toLowerCase();
  return MOCK_MOVIES.filter(
    (m) => m.title.toLowerCase().includes(q) || m.overview.toLowerCase().includes(q)
  ).map(m => ({ ...m, media_type: "movie" as const }));
}

// TV Show Mock Functions
export function getTrendingTv(): Movie[] {
  return [...MOCK_TV_SHOWS].sort((a, b) => b.popularity - a.popularity).slice(0, 20).map(m => {
    const result: Movie = { ...m, media_type: "tv" as const };
    return result;
  });
}

export function getPopularTv(): Movie[] {
  return [...MOCK_TV_SHOWS].sort((a, b) => b.popularity - a.popularity).slice(0, 20).map(m => {
    const result: Movie = { ...m, media_type: "tv" as const };
    return result;
  });
}

export function getTopRatedTv(): Movie[] {
  return [...MOCK_TV_SHOWS].sort((a, b) => b.vote_average - a.vote_average).slice(0, 20).map(m => {
    const result: Movie = { ...m, media_type: "tv" as const };
    return result;
  });
}

export function searchTv(query: string): Movie[] {
  const q = query.toLowerCase();
  return MOCK_TV_SHOWS.filter(
    (m) => (m.title || m.name || "").toLowerCase().includes(q) || m.overview.toLowerCase().includes(q)
  ).map(m => {
    const result: Movie = { ...m, media_type: "tv" as const };
    return result;
  });
}

export const TMDB_IMAGE_BASE = "https://image.tmdb.org/t/p";

export function getPosterUrl(path: string | null, size: "w342" | "w500" | "w780" = "w500"): string {
  if (!path) return `https://picsum.photos/seed/movie${size}/300/450`;
  return `${TMDB_IMAGE_BASE}/${size}${path}`;
}

export function getBackdropUrl(path: string | null, size: "w780" | "w1280" | "original" = "w1280"): string {
  if (!path) return `https://picsum.photos/seed/backdrop${size}/1280/720`;
  return `${TMDB_IMAGE_BASE}/${size}${path}`;
}

export function getProfileUrl(path: string | null): string {
  if (!path) return `https://picsum.photos/seed/profile185/200/300`;
  return `${TMDB_IMAGE_BASE}/w185${path}`;
}

export function getEpisodeStillUrl(path: string | null, size: "w300" | "w500" | "w780" = "w500"): string {
  if (!path) return `https://picsum.photos/seed/episode${size}/720/405`;
  return `${TMDB_IMAGE_BASE}/${size}${path}`;
}
